[package]
name = "eliecs"
version = "0.1.0"
edition = "2021"

[dependencies]
eliecs_macros = { path = "../eliecs_macros" }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "pools"
harness = false
